language: objective-c
osx_image: xcode9

env:
  matrix:
    - SCHEME=StackLayout       SDK=iphonesimulator11.0

before_install:
#  - brew outdated xctool || brew upgrade xctool;
  - gem install xcpretty-travis-formatter;
  - gem install cocoapods --no-document --quiet;
#  - pod repo update --silent;
  - pod install --repo-update;

script:
  - set -o pipefail && xcodebuild -workspace StackLayout.xcworkspace -scheme "$SCHEME" -sdk $SDK -destination 'platform=iOS Simulator,name=iPhone 6' -enableCodeCoverage YES build test | xcpretty -f `xcpretty-travis-formatter`
      bundle exec fastlane travis

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'StackLayout' -J 'StackLayoutTests'
