language: objective-c
osx_image: xcode9.1s

# env:
#   matrix:
    # - SCHEME=StackLayout       SDK=iphonesimulator11.1

before_install:
#  - brew outdated xctool || brew upgrade xctool;
  - gem install xcpretty-travis-formatter;
  - gem install cocoapods --no-document --quiet;
#  - pod repo update --silent;
  - pod install --repo-update;

script:
  - set -o pipefail && bundle exec fastlane travis

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'StackLayout' -J 'StackLayoutTests'
