language: objective-c
osx_image: xcode11.2

cache:
  - bundler
  - cocoapods

install:
  - bundle install # --deployment # to cache vendor/bundle
  - pod install --repo-update;

script:
  - sh build-ci.sh /tmp/StackViewLayout

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'StackLayout' -J 'StackLayoutTests'
